import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import { theme } from "./styles/theme";

export const metadata = {
  title: "UTN 2024 - DAN app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Import Lato font from Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline /> {/* Normalize styles across browsers */}
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}