export const metadata = {
  title: "UTN 2024 - DAN app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
        {children}
        </div>
      </body>
    </html>
  );
}
