export const metadata = {
  title: "UTN 2024 - DAN app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          padding: 0,
          minHeight: "100vh",
          background: "linear-gradient(135deg, #dbeafe, #fef9c3)", // Apply the gradient here
        }}
      >
        <div>{children}</div>
      </body>
    </html>
  );
}