services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: clientes-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpw
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - clientes-net

  phpmyadmin-dan:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql-db
      PMA_USER: admin
      PMA_PASSWORD: adminpw
    ports:
      - "8086:80"
    depends_on:
      - mysql
    networks:
      - clientes-net
  ms-clientes-svc-1:
    image: ms-clientes-svc:latest
    # container_name: ms-clientes-svc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/clientes-db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: adminpw
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_EUREKA_DEFAULT_ZONE: http://ms-eureka-svc:8761/eureka/
      SPRING_INSTANCIA: ms-clientes-svc-1
    ports:
      - "6080:8080"
    depends_on:
      - mysql
    networks:
      - clientes-net
      - backend-net

  ms-clientes-svc-2:
    image: ms-clientes-svc:latest
    # container_name: ms-clientes-svc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/clientes-db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: adminpw
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_EUREKA_DEFAULT_ZONE: http://ms-eureka-svc:8761/eureka/
      SPRING_INSTANCIA: ms-clientes-svc-2
    ports:
      - "6081:8080"
    depends_on:
      - mysql
    networks:
      - clientes-net
      - backend-net

  ms-clientes-svc-3:
    image: ms-clientes-svc:latest
    # container_name: ms-clientes-svc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/clientes-db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: adminpw
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_EUREKA_DEFAULT_ZONE: http://ms-eureka-svc:8761/eureka/
      SPRING_INSTANCIA: ms-clientes-svc-3
    ports:
      - "6082:8080"
    depends_on:
      - mysql
    networks:
      - clientes-net
      - backend-net

networks:
  backend-net:
    external: true
  clientes-net:
    driver: bridge

volumes:
  mysql-data:
